landingpage/urls.py
from django.urls import path

#local imports
from landingpage import views as landingpage_views

urlpatterns = [
    # path('', landingpage_views.ProjectView.as_view(), name='project'),
    path('', landingpage_views.HomePageView.as_view(), name='home'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('timeline/', include('timeline.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

timeline/urls.py
from django.urls import path

#local imports
from timeline import views as timeline_views

urlpatterns = [
    path('', timeline_views.CardView.as_view(), name='timeline-home'),
]

download_resume_pdf/models.py
from django.db import models

# Create your models here.
class ResumeLink(models.Model):
    url = models.URLField()
    name = models.CharField(max_length=255, blank=False, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # TODO: there should only be one active resume at a time.
    is_active = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # unset is_active of all other resume to false,
        
        if self.is_active:
            activeResumes = ResumeLink.objects.filter(is_active=True)
            for resume in activeResumes:
                resume.is_active = False
            ResumeLink.objects.bulk_update(activeResumes, ['is_active'])
        super(ResumeLink, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name[:30]}.. url:{self.url[:30]}"

landingpage/models.py
from django.db import models
from timeline.models import Link
from django.utils import timezone

# Create your models here.
class Project(models.Model):
    heading = models.CharField(max_length=55, default="I forgot to add heading..", blank=False, null=False)
    body = models.TextField(max_length=999, default="", null=True, blank=True)
    start_date = models.DateField(default=timezone.now, null=False, blank=False)
    end_date = models.DateField(default=timezone.now, null=False, blank=False)
    image_link = models.ForeignKey(Link, on_delete=models.SET_NULL, null=True, blank=True, related_name='image_link')
    live_link = models.ForeignKey(Link, on_delete=models.SET_NULL, null=True, blank=True, related_name='live_link')
    details_link = models.ForeignKey(Link, on_delete=models.SET_NULL, null=True, blank=True, related_name='details_link')
    
    def __str__(self) -> str:
        return f"{self.heading}.. start: {self.start_date}, end:{self.end_date}"

timeline/models.py
from django.db import models 
from django.utils import timezone

class Link(models.Model):
    url = models.URLField()
    name = models.CharField(default="", null=True, blank=True, max_length=999)

    def __str__(self):
        return self.url

class Card(models.Model):
    """
    In timeline: Each achievement is shown in card
    """
    heading = models.CharField(max_length=55, default="I forgot to add heading..", blank=False, null=False)
    body = models.TextField(max_length=999, default="", null=True, blank=True)
    date = models.DateField(default=timezone.now, null=False, blank=False)
    link = models.ForeignKey(Link, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.heading}.. on {self.date}"

download_resume_pdf/views.py
from django.shortcuts import render

# Create your views here.

landingpage/views.py
from django.shortcuts import render
from django.views.generic import View

# models
from landingpage.models import Project
from download_resume_pdf.models import ResumeLink

# Create your views here.

class HomePageView(View):
    template_name = 'landingpage/index.html'

    def get(self, request):
        activeResumes = ResumeLink.objects.filter(is_active=True)
        qs = {
            'project_data':Project.objects.all(),
            'resume_url': (activeResumes[0] if len(activeResumes) else [])
        }
        return render(request, self.template_name, context=qs)

class ProjectView(View):
    template_name = 'landingpage/portfolio-details.html'
    def get(self, request):
        return render(request, self.template_name)

timeline/views.py
from typing import List
from django.shortcuts import render
from django.views.generic import ListView, View
# local imports
from timeline.models import Card, Link
from django.forms.models import model_to_dict

# general imports
from collections import defaultdict

# Create your views here.

class CardView(View):
    template_name = 'timeline/card_list_view.html'
    def get(self, request):
        cards = Card.objects.all().order_by('-date')

        qs = defaultdict(list)
        for query in cards:
            card_year = query.date.year
            query_dict = model_to_dict(query)
            query_dict['link'] = query.link.url if (query.link is not None) else None
            qs[card_year] += [query_dict]
        qs = dict(qs)
        return render(request, template_name=self.template_name, context={'timeline_data':qs})

landingpage/templates/landingpage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Portfolio Aman Goyal - Home</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!--icons-->
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    <script src="https://kit.fontawesome.com/da103a00e4.js" crossorigin="anonymous"></script>

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'landingpage/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'landingpage/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'landingpage/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'landingpage/favicon/site.webmanifest' %}">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'landingpage/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'landingpage/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'landingpage/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'landingpage/vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'landingpage/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'landingpage/vendor/aos/aos.css' %}" rel="stylesheet">

    {% block head %}
    {% endblock head %}

    <!-- Template Main CSS File --> 
    <link href="{% static 'landingpage/css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
  * Template Name: iPortfolio - v1.5.0
  * Template URL: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <!-- ======= Mobile nav toggle button ======= -->
    <button type="button" class="mobile-nav-toggle d-xl-none"><i class="icofont-navigation-menu"></i></button>

    <!-- ======= Header ======= -->
    <header id="header">
        <div class="d-flex flex-column">

            <div class="profile">
                <img src="{% static 'landingpage/img/aman-prof-square-image.jpg' %}" alt="" class="img-fluid rounded-circle">
                <h1 class="text-light"><a href="{% url 'home' %}#main">Aman Goyal</a></h1>
                <div class="social-links mt-3 text-center">
                    <!-- <a href="https://twitter.com/_goyalaman" class="twitter"><i class="bx bxl-twitter"></i></a> -->
                    <!-- <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a> -->
                    <!-- <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a> -->
                    <!-- <a href="{% url 'timeline-home' %}" class="google-plus"><i class="bx bxl-skype"></i></a> -->
                    <!-- <a href="https://www.linkedin.com/in/ln-amangoyal/" class="linkedin"><i class="bx bxl-linkedin"></i></a> -->
                    <!-- <a href="https://dev.to/goyalaman" class="devto"><i class="bx bxl-dev-to"></i></a> -->
                    <!-- <a href="https://blog.amangoyal.ml/" class="devto"> -->
                        <!-- <iconify-icon data-icon="cib-hashnode"></iconify-icon></i> -->
                    <!-- </a> -->
                    <!-- <a href="https://github.com/goyal-aman" class="bx-bxl-github"><i class="bx bxl-github"></i></a> -->
                </div>
            </div>

            <nav class="nav-menu">
                <ul>
                    <li class="active"><a href="{% url 'home'  %}#main"><i class="bx bx-home"></i> <span>Home</span></a>
                    </li>
                    <li><a href="{% url 'home' %}#about"><i class="bx bx-user"></i> <span>About</span></a></li>
                    <li><a href="{% url 'home' %}#stats"><i class="bx bx-stats"></i> <span>Stats</span></a></li>
                    <li><a href="{% url 'home' %}#resume"><i class="bx bx-file-blank"></i> <span>Resume</span></a></li>
                    <li><a href="{% url 'home' %}#skills"><i class="bx bx-bulb"></i> <span>Skills</span></a></li>
                    <li><a href="{% url 'home' %}#projects"><i class="bx bx-server"></i> Projects</a></li>
                    <li><a href="{% url 'home' %}#contact"><i class="bx bx-envelope"></i> Contact</a></li>
                    <hr color="grey">
                    <li><a href="{% url 'timeline-home' %}"><i class="bx bx-book-content"></i> Timeline</a></li>
                </ul>
            </nav><!-- .nav-menu -->
            <button type="button" class="mobile-nav-toggle d-xl-none"><i class="icofont-navigation-menu"></i></button>

        </div>
    </header><!-- End Header -->

    {% block content %}
    {% endblock content %}
    <!-- ======= Footer ======= -->

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'landingpage/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'landingpage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'landingpage/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'landingpage/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'landingpage/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'landingpage/vendor/counterup/counterup.min.js'  %}"></script>
    <script src="{% static 'landingpage/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'landingpage/vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static 'landingpage/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'landingpage/vendor/typed.js/typed.min.js' %}"></script>
    <script src="{% static 'landingpage/vendor/aos/aos.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'landingpage/js/main.js' %}"></script>

</body>

</html>

landingpage/templates/landingpage/inner-page.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Inner Page - iPortfolio Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
  <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: iPortfolio - v1.5.0
  * Template URL: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Mobile nav toggle button ======= -->
  <button type="button" class="mobile-nav-toggle d-xl-none"><i class="icofont-navigation-menu"></i></button>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="d-flex flex-column">

      <div class="profile">
        <img src="assets/img/profile-img.jpg" alt="" class="img-fluid rounded-circle">
        <h1 class="text-light"><a href="index.html">Alex Smith</a></h1>
        <div class="social-links mt-3 text-center">
          <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
          <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>

      <nav class="nav-menu">
        <ul>
          <li><a href="index.html"><i class="bx bx-home"></i> <span>Home</span></a></li>
          <li><a href="#about"><i class="bx bx-user"></i> <span>About</span></a></li>
          <li><a href="#resume"><i class="bx bx-file-blank"></i> <span>Resume</span></a></li>
          <li><a href="#portfolio"><i class="bx bx-book-content"></i> Portfolio</a></li>
          <li><a href="#services"><i class="bx bx-server"></i> Services</a></li>
          <li><a href="#contact"><i class="bx bx-envelope"></i> Contact</a></li>

        </ul>
      </nav><!-- .nav-menu -->
      <button type="button" class="mobile-nav-toggle d-xl-none"><i class="icofont-navigation-menu"></i></button>

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Inner Page</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Inner Page</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <p>
          Example inner page template
        </p>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>iPortfolio</span></strong>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/typed.js/typed.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>

landingpage/templates/landingpage/portfolio-details.html
{% extends 'landingpage/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Portfolio Details - iPortfolio Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'landingpage/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'landingpage/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
  <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: iPortfolio - v1.5.0
  * Template URL: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Mobile nav toggle button ======= -->
  <button type="button" class="mobile-nav-toggle d-xl-none"><i class="icofont-navigation-menu"></i></button>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="d-flex flex-column">

      <div class="profile">
        <img src="assets/img/profile-img.jpg" alt="" class="img-fluid rounded-circle">
        <h1 class="text-light"><a href="index.html">Alex Smith</a></h1>
        <div class="social-links mt-3 text-center">
          <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
          <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>

      <nav class="nav-menu">
        <ul>
          <li><a href="index.html"><i class="bx bx-home"></i> <span>Home</span></a></li>
          <li><a href="#about"><i class="bx bx-user"></i> <span>About</span></a></li>
          <li><a href="#resume"><i class="bx bx-file-blank"></i> <span>Resume</span></a></li>
          <li class="active"><a href="#portfolio"><i class="bx bx-book-content"></i> Portfolio</a></li>
          <li><a href="#services"><i class="bx bx-server"></i> Services</a></li>
          <li><a href="#contact"><i class="bx bx-envelope"></i> Contact</a></li>

        </ul>
      </nav><!-- .nav-menu -->
      <button type="button" class="mobile-nav-toggle d-xl-none"><i class="icofont-navigation-menu"></i></button>

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Portfoio Details</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Portfoio Details</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="portfolio-details-container">

          <div class="owl-carousel portfolio-details-carousel">
            <img src="{% static 'landingpage/img/portfolio/portfolio-1.jpg' %}" class="img-fluid" alt="">
            <img src="{% static 'landingpage/img/portfolio/portfolio-4.jpg' %}" class="img-circle" alt="">
            <img src="{% static 'landingpage/assets/img/portfolio-details-1.png' %}" class="img-fluid" alt="">
          </div>

          <div class="portfolio-info">
            <h3>Project information</h3>
            <ul>
              <li><strong>Category</strong>: Web design</li>
              <li><strong>Client</strong>: ASU Company</li>
              <li><strong>Project date</strong>: 01 March, 2020</li>
              <li><strong>Project URL</strong>: <a href="#">www.example.com</a></li>
            </ul>
          </div>

        </div>

        <div class="portfolio-description">
          <h2>This is an example of portfolio detail</h2>
          <p>
            Autem ipsum nam porro corporis rerum. Quis eos dolorem eos itaque inventore commodi labore quia quia. Exercitationem repudiandae officiis neque suscipit non officia eaque itaque enim. Voluptatem officia accusantium nesciunt est omnis tempora consectetur dignissimos. Sequi nulla at esse enim cum deserunt eius.
          </p>
        </div>

      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>iPortfolio</span></strong>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/jquery/jquery.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
  <script src="assets/vendor/counterup/counterup.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/venobox/venobox.min.js"></script>
  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="assets/vendor/typed.js/typed.min.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'landingpage/assets/js/main.js' %}"></script>

</body>

</html>

{% endblock content %}

landingpage/templates/landingpage/snippets/project_card.html
{% load static %}
<div class="col-lg-4 col-md-6 portfolio-item filter-text" >
    <div class="portfolio-wrap">

        <!-- TODO : add defualt image url -->
        <!-- THIS IS PROJECT THUMBNAIL -->
        <img src={{url}} class="img-fluid" alt="" style="width: 100%; height: 20vh; border-top-left-radius: 10px; border-top-right-radius: 10px;">


        <div class="portfolio-links">
            {% if live_link %}
                <a href="{{live_link}}" data-gall="portfolioGallery" class="" title="Live Project"><i class="bx bx-plus"></i></a>
            {% endif %}
            {% if details_link %}
                <a href="{{details_link}}" title="More Details"><i class="bx bxs-file"></i></a>
            {% endif %}
        </div>
        <h6 style="align-items: center; text-align: left; padding-top:5px; padding-left:1px; padding-bottom:5px; background-color: rgb(2, 6, 73); color:white; s"><b>{{heading|title}}</b></h6>
    </div>
</div>

timeline/templates/timeline/card_list_view.html
{% extends 'landingpage/base.html' %}
{% load static %}

{% block head %}
<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css'>
<link rel="stylesheet" href="{% static 'timeline/style.css' %}">
{% endblock head %}

{% block content %}
<main id="main">

    <section class="inner-page">
        <div class="container">

            <div class="section-title">
                <h2>Timline</h2>
                <p>Track record of my minor and major professional achievements.</p>
            </div>


            <!--new additions above-->

            <!-- partial:index.partial.html -->
            <div class="timeline">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="timeline-container">

                                <div class="timeline-end">
                                    <p>Now</p>
                                </div>

                                <div class="timeline-continue">
                                    {% for year, card_list in timeline_data.items %}
                                    {% for card in card_list %}
                                    {% if forloop.counter|divisibleby:2 %}
                                    {% include 'timeline/snippets/right_card.html' with heading=card.heading date=card.date body=card.body url=card.link %}
                                    {% else %}
                                    {% include 'timeline/snippets/left_card.html' with heading=card.heading date=card.date body=card.body url=card.link %}
                                    {% endif %}
                                    {% endfor %}
                                    {% include 'timeline/snippets/year_circle.html' with year=year %}
                                    {% endfor %}
                                </div>

                                <div class="timeline-start">
                                    <p>Launch</p>
                                </div>

                                <div class="timeline-launch">
                                    <div class="timeline-box">
                                        <div class="timeline-text">
                                            <h3>Launched my timeline</h3>
                                            <p></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- partial -->
{% endblock content %}

timeline/templates/timeline/snippets/year_circle.html
<div class="row">
    <div class="col-12">
        <div class="timeline-year">
            <p>{{year}}</p>
        </div>
    </div>
</div>